name: FreemanTools
version: 1.1
main: com.github.freeman21.FreemanTools.FreemanTools
   
softdepend: [Vault]

commands:
  blockhead:
      description: Put the block on your head.
      usage: /<command>
  FreemanToolsVersion:
      description: Shows the version.
      usage: /<command>