name: FreemanTools
version: 1.2
main: com.github.freeman21.FreemanTools.FreemanTools
   
softdepend: [Vault]

commands:
  blockhead:
      description: Put the block on your head.
      usage: /<command>
      aliases: [bh]
  FreemanToolsVersion:
      description: Shows the version.
      aliases: [ftv]
      usage: /<command>