name: FreemanTools
version: 1.3
main: com.freeman21.bukkit.FreemanTools
   
softdepend: [Vault]

commands:
  blockhead:
      description: Put the block on your head.
      usage: /<command>
      aliases: [bh]
  FreemanToolsVersion:
      description: Shows the version.
      aliases: [ftv]
      usage: /<command>